### ISSUE TITLE
pip install on windows fails

### ISSUE THREAD

**Issue by Didou09** [ToFuProject/tofu#63]
tofu is not yet available as a pre-compiled conda package for windows 64 bits, so Arpan tried to install it using pip instead.
After creating a virtual environment dedicated to that installation, and running pip (from the conda pip), the following happened (see png attached):

**> pip install tofu**
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\napra\AppData\Local\Temp\pip-install-6rkhfbb8\tofu\setup.py", line 70, in <module>
        not_openmp_installed = check_for_openmp(os.environ['CC'])
      File "C:\Users\napra\AppData\Local\Temp\pip-install-6rkhfbb8\tofu\setup.py", line 43, in check_for_openmp
        stdout=fnull, stderr=fnull)
      File "C:\Users\napra\Anaconda3\envs\tofu140\lib\subprocess.py", line 317, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\napra\Anaconda3\envs\tofu140\lib\subprocess.py", line 769, in __init__
        restore_signals, start_new_session)
      File "C:\Users\napra\Anaconda3\envs\tofu140\lib\subprocess.py", line 1172, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\napra\AppData\Local\Temp\pip-install-6rkhfbb8\tofu\

![tofu installation issue](https://user-images.githubusercontent.com/5929562/57779437-5cbf1500-7726-11e9-9348-b6d3c73f3bc4.PNG)

**Comment by Didou09** [comment]
Fixed in devel by PR #143

**Comment by Didou09** [comment]
Closed in 1.4.1
